INSERT INTO vets VALUES (default, 'James', 'Carter');
INSERT INTO vets VALUES (default, 'Helen', 'Leary');
INSERT INTO vets VALUES (default, 'Linda', 'Douglas');
INSERT INTO vets VALUES (default, 'Rafael', 'Ortega');
INSERT INTO vets VALUES (default, 'Henry', 'Stevens');
INSERT INTO vets VALUES (default, 'Sharon', 'Jenkins');

INSERT INTO specialties VALUES (default, 'radiology');
INSERT INTO specialties VALUES (default, 'surgery');
INSERT INTO specialties VALUES (default, 'dentistry');

INSERT INTO vet_specialties VALUES (2, 1);
INSERT INTO vet_specialties VALUES (3, 2);
INSERT INTO vet_specialties VALUES (3, 3);
INSERT INTO vet_specialties VALUES (4, 2);
INSERT INTO vet_specialties VALUES (5, 1);

INSERT INTO types VALUES (default, 'cat');
INSERT INTO types VALUES (default, 'dog');
INSERT INTO types VALUES (default, 'lizard');
INSERT INTO types VALUES (default, 'snake');
INSERT INTO types VALUES (default, 'bird');
INSERT INTO types VALUES (default, 'hamster');

INSERT INTO owners VALUES (default, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT INTO owners VALUES (default, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT INTO owners VALUES (default, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT INTO owners VALUES (default, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT INTO owners VALUES (default, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT INTO owners VALUES (default, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT INTO owners VALUES (default, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT INTO owners VALUES (default, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT INTO owners VALUES (default, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT INTO owners VALUES (default, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT INTO pets VALUES (default, 'Leo', '2010-09-07', 1, 1);
INSERT INTO pets VALUES (default, 'Basil', '2012-08-06', 6, 2);
INSERT INTO pets VALUES (default, 'Rosy', '2011-04-17', 2, 3);
INSERT INTO pets VALUES (default, 'Jewel', '2010-03-07', 2, 3);
INSERT INTO pets VALUES (default, 'Iggy', '2010-11-30', 3, 4);
INSERT INTO pets VALUES (default, 'George', '2010-01-20', 4, 5);
INSERT INTO pets VALUES (default, 'Samantha', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (default, 'Max', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (default, 'Lucky', '2011-08-06', 5, 7);
INSERT INTO pets VALUES (default, 'Mulligan', '2007-02-24', 2, 8);
INSERT INTO pets VALUES (default, 'Freddy', '2010-03-09', 5, 9);
INSERT INTO pets VALUES (default, 'Lucky', '2010-06-24', 2, 10);
INSERT INTO pets VALUES (default, 'Sly', '2012-06-08', 1, 10);

INSERT INTO visits VALUES (default, 7, '2013-01-01', 'rabies shot');
INSERT INTO visits VALUES (default, 8, '2013-01-02', 'rabies shot');
INSERT INTO visits VALUES (default, 8, '2013-01-03', 'neutered');
INSERT INTO visits VALUES (default, 7, '2013-01-04', 'spayed');

INSERT INTO drugs VALUES (default, 'Amoxicillin', 'Antibiotic', 'Tablet', 18.50, 'Broad-spectrum antibiotic for common bacterial infections.');
INSERT INTO drugs VALUES (default, 'Clavamox', 'Antibiotic', 'Tablet', 24.99, 'Combination antibiotic for skin and dental infections.');
INSERT INTO drugs VALUES (default, 'Cefpodoxime', 'Antibiotic', 'Tablet', 31.75, 'Once-daily cephalosporin for canine skin infections.');
INSERT INTO drugs VALUES (default, 'Doxycycline', 'Antibiotic', 'Capsule', 19.90, 'Tetracycline antibiotic often used for tick-borne diseases.');
INSERT INTO drugs VALUES (default, 'Cefovecin', 'Antibiotic', 'Injectable', 57.25, 'Long-acting injectable antibiotic for cats and dogs.');
INSERT INTO drugs VALUES (default, 'Milbemycin', 'Antiparasitic', 'Tablet', 14.25, 'Monthly heartworm prevention with intestinal parasite coverage.');
INSERT INTO drugs VALUES (default, 'Fenbendazole', 'Antiparasitic', 'Suspension', 12.80, 'Dewormer for roundworms, hookworms, and giardia.');
INSERT INTO drugs VALUES (default, 'Selamectin', 'Antiparasitic', 'Topical', 22.40, 'Topical treatment for fleas, ear mites, and heartworm prevention.');
INSERT INTO drugs VALUES (default, 'Pyrantel Pamoate', 'Antiparasitic', 'Suspension', 9.60, 'Oral dewormer commonly used in puppies and kittens.');
INSERT INTO drugs VALUES (default, 'Ivermectin', 'Antiparasitic', 'Injectable', 16.30, 'Antiparasitic used for mange and parasite control.');
INSERT INTO drugs VALUES (default, 'Carprofen', 'Pain Management', 'Chewable', 28.45, 'NSAID chewable for canine postoperative pain.');
INSERT INTO drugs VALUES (default, 'Gabapentin', 'Pain Management', 'Capsule', 17.20, 'Neuropathic pain support and mild anxiolytic.');
INSERT INTO drugs VALUES (default, 'Tramadol', 'Pain Management', 'Tablet', 21.15, 'Oral analgesic for short-term pain relief.');
INSERT INTO drugs VALUES (default, 'Buprenorphine', 'Pain Management', 'Injectable', 34.80, 'Opioid analgesic for moderate pain control.');
INSERT INTO drugs VALUES (default, 'Amantadine', 'Pain Management', 'Capsule', 13.95, 'Adjunct pain medication for chronic discomfort.');
INSERT INTO drugs VALUES (default, 'Meloxicam', 'Anti-inflammatory', 'Suspension', 23.50, 'Oral NSAID for inflammation and osteoarthritis pain.');
INSERT INTO drugs VALUES (default, 'Deracoxib', 'Anti-inflammatory', 'Chewable', 29.10, 'COX-2 selective NSAID for canine inflammation.');
INSERT INTO drugs VALUES (default, 'Firocoxib', 'Anti-inflammatory', 'Tablet', 33.60, 'Once-daily anti-inflammatory for osteoarthritis.');
INSERT INTO drugs VALUES (default, 'Prednisolone', 'Anti-inflammatory', 'Tablet', 11.75, 'Corticosteroid for inflammatory and immune-mediated conditions.');
INSERT INTO drugs VALUES (default, 'Triamcinolone', 'Anti-inflammatory', 'Injectable', 26.55, 'Injectable corticosteroid for acute inflammatory flare-ups.');
INSERT INTO drugs VALUES (default, 'Chlorhexidine Spray', 'Dermatology', 'Topical', 15.40, 'Antiseptic spray for superficial skin infections.');
INSERT INTO drugs VALUES (default, 'Mupirocin', 'Dermatology', 'Ointment', 18.90, 'Topical antibiotic ointment for localized lesions.');
INSERT INTO drugs VALUES (default, 'Ketoconazole Shampoo', 'Dermatology', 'Shampoo', 27.35, 'Medicated shampoo for fungal and seborrheic skin disease.');
INSERT INTO drugs VALUES (default, 'Oclacitinib', 'Dermatology', 'Tablet', 42.70, 'Anti-itch therapy for allergic dermatitis.');
INSERT INTO drugs VALUES (default, 'Lime Sulfur Dip', 'Dermatology', 'Topical', 13.20, 'Dip treatment for ringworm and external parasites.');
INSERT INTO drugs VALUES (default, 'Cerenia', 'Gastrointestinal', 'Tablet', 36.25, 'Anti-nausea medication for vomiting and motion sickness.');
INSERT INTO drugs VALUES (default, 'Omeprazole', 'Gastrointestinal', 'Capsule', 10.80, 'Acid reducer for gastritis and reflux support.');
INSERT INTO drugs VALUES (default, 'Metronidazole', 'Gastrointestinal', 'Tablet', 16.95, 'Antimicrobial often used for diarrhea and giardia.');
INSERT INTO drugs VALUES (default, 'Sucralfate', 'Gastrointestinal', 'Suspension', 14.60, 'Gastroprotectant for esophageal and stomach irritation.');
INSERT INTO drugs VALUES (default, 'Probiotic Paste', 'Gastrointestinal', 'Paste', 12.10, 'Digestive support paste for stress-related diarrhea.');
