INSERT IGNORE INTO vets VALUES (1, 'James', 'Carter');
INSERT IGNORE INTO vets VALUES (2, 'Helen', 'Leary');
INSERT IGNORE INTO vets VALUES (3, 'Linda', 'Douglas');
INSERT IGNORE INTO vets VALUES (4, 'Rafael', 'Ortega');
INSERT IGNORE INTO vets VALUES (5, 'Henry', 'Stevens');
INSERT IGNORE INTO vets VALUES (6, 'Sharon', 'Jenkins');

INSERT IGNORE INTO specialties VALUES (1, 'radiology');
INSERT IGNORE INTO specialties VALUES (2, 'surgery');
INSERT IGNORE INTO specialties VALUES (3, 'dentistry');

INSERT IGNORE INTO vet_specialties VALUES (2, 1);
INSERT IGNORE INTO vet_specialties VALUES (3, 2);
INSERT IGNORE INTO vet_specialties VALUES (3, 3);
INSERT IGNORE INTO vet_specialties VALUES (4, 2);
INSERT IGNORE INTO vet_specialties VALUES (5, 1);

INSERT IGNORE INTO types VALUES (1, 'cat');
INSERT IGNORE INTO types VALUES (2, 'dog');
INSERT IGNORE INTO types VALUES (3, 'lizard');
INSERT IGNORE INTO types VALUES (4, 'snake');
INSERT IGNORE INTO types VALUES (5, 'bird');
INSERT IGNORE INTO types VALUES (6, 'hamster');

INSERT IGNORE INTO owners VALUES (1, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT IGNORE INTO owners VALUES (2, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT IGNORE INTO owners VALUES (3, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT IGNORE INTO owners VALUES (4, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT IGNORE INTO owners VALUES (5, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT IGNORE INTO owners VALUES (6, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT IGNORE INTO owners VALUES (7, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT IGNORE INTO owners VALUES (8, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT IGNORE INTO owners VALUES (9, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT IGNORE INTO owners VALUES (10, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT IGNORE INTO pets VALUES (1, 'Leo', '2000-09-07', 1, 1);
INSERT IGNORE INTO pets VALUES (2, 'Basil', '2002-08-06', 6, 2);
INSERT IGNORE INTO pets VALUES (3, 'Rosy', '2001-04-17', 2, 3);
INSERT IGNORE INTO pets VALUES (4, 'Jewel', '2000-03-07', 2, 3);
INSERT IGNORE INTO pets VALUES (5, 'Iggy', '2000-11-30', 3, 4);
INSERT IGNORE INTO pets VALUES (6, 'George', '2000-01-20', 4, 5);
INSERT IGNORE INTO pets VALUES (7, 'Samantha', '1995-09-04', 1, 6);
INSERT IGNORE INTO pets VALUES (8, 'Max', '1995-09-04', 1, 6);
INSERT IGNORE INTO pets VALUES (9, 'Lucky', '1999-08-06', 5, 7);
INSERT IGNORE INTO pets VALUES (10, 'Mulligan', '1997-02-24', 2, 8);
INSERT IGNORE INTO pets VALUES (11, 'Freddy', '2000-03-09', 5, 9);
INSERT IGNORE INTO pets VALUES (12, 'Lucky', '2000-06-24', 2, 10);
INSERT IGNORE INTO pets VALUES (13, 'Sly', '2002-06-08', 1, 10);

INSERT IGNORE INTO visits VALUES (1, 7, '2010-03-04', 'rabies shot');
INSERT IGNORE INTO visits VALUES (2, 8, '2011-03-04', 'rabies shot');
INSERT IGNORE INTO visits VALUES (3, 8, '2009-06-04', 'neutered');
INSERT IGNORE INTO visits VALUES (4, 7, '2008-09-04', 'spayed');

INSERT IGNORE INTO drugs VALUES (1, 'Amoxicillin', 'Antibiotic', 'Tablet', 18.50, 'Broad-spectrum antibiotic for common bacterial infections.');
INSERT IGNORE INTO drugs VALUES (2, 'Clavamox', 'Antibiotic', 'Tablet', 24.99, 'Combination antibiotic for skin and dental infections.');
INSERT IGNORE INTO drugs VALUES (3, 'Cefpodoxime', 'Antibiotic', 'Tablet', 31.75, 'Once-daily cephalosporin for canine skin infections.');
INSERT IGNORE INTO drugs VALUES (4, 'Doxycycline', 'Antibiotic', 'Capsule', 19.90, 'Tetracycline antibiotic often used for tick-borne diseases.');
INSERT IGNORE INTO drugs VALUES (5, 'Cefovecin', 'Antibiotic', 'Injectable', 57.25, 'Long-acting injectable antibiotic for cats and dogs.');
INSERT IGNORE INTO drugs VALUES (6, 'Milbemycin', 'Antiparasitic', 'Tablet', 14.25, 'Monthly heartworm prevention with intestinal parasite coverage.');
INSERT IGNORE INTO drugs VALUES (7, 'Fenbendazole', 'Antiparasitic', 'Suspension', 12.80, 'Dewormer for roundworms, hookworms, and giardia.');
INSERT IGNORE INTO drugs VALUES (8, 'Selamectin', 'Antiparasitic', 'Topical', 22.40, 'Topical treatment for fleas, ear mites, and heartworm prevention.');
INSERT IGNORE INTO drugs VALUES (9, 'Pyrantel Pamoate', 'Antiparasitic', 'Suspension', 9.60, 'Oral dewormer commonly used in puppies and kittens.');
INSERT IGNORE INTO drugs VALUES (10, 'Ivermectin', 'Antiparasitic', 'Injectable', 16.30, 'Antiparasitic used for mange and parasite control.');
INSERT IGNORE INTO drugs VALUES (11, 'Carprofen', 'Pain Management', 'Chewable', 28.45, 'NSAID chewable for canine postoperative pain.');
INSERT IGNORE INTO drugs VALUES (12, 'Gabapentin', 'Pain Management', 'Capsule', 17.20, 'Neuropathic pain support and mild anxiolytic.');
INSERT IGNORE INTO drugs VALUES (13, 'Tramadol', 'Pain Management', 'Tablet', 21.15, 'Oral analgesic for short-term pain relief.');
INSERT IGNORE INTO drugs VALUES (14, 'Buprenorphine', 'Pain Management', 'Injectable', 34.80, 'Opioid analgesic for moderate pain control.');
INSERT IGNORE INTO drugs VALUES (15, 'Amantadine', 'Pain Management', 'Capsule', 13.95, 'Adjunct pain medication for chronic discomfort.');
INSERT IGNORE INTO drugs VALUES (16, 'Meloxicam', 'Anti-inflammatory', 'Suspension', 23.50, 'Oral NSAID for inflammation and osteoarthritis pain.');
INSERT IGNORE INTO drugs VALUES (17, 'Deracoxib', 'Anti-inflammatory', 'Chewable', 29.10, 'COX-2 selective NSAID for canine inflammation.');
INSERT IGNORE INTO drugs VALUES (18, 'Firocoxib', 'Anti-inflammatory', 'Tablet', 33.60, 'Once-daily anti-inflammatory for osteoarthritis.');
INSERT IGNORE INTO drugs VALUES (19, 'Prednisolone', 'Anti-inflammatory', 'Tablet', 11.75, 'Corticosteroid for inflammatory and immune-mediated conditions.');
INSERT IGNORE INTO drugs VALUES (20, 'Triamcinolone', 'Anti-inflammatory', 'Injectable', 26.55, 'Injectable corticosteroid for acute inflammatory flare-ups.');
INSERT IGNORE INTO drugs VALUES (21, 'Chlorhexidine Spray', 'Dermatology', 'Topical', 15.40, 'Antiseptic spray for superficial skin infections.');
INSERT IGNORE INTO drugs VALUES (22, 'Mupirocin', 'Dermatology', 'Ointment', 18.90, 'Topical antibiotic ointment for localized lesions.');
INSERT IGNORE INTO drugs VALUES (23, 'Ketoconazole Shampoo', 'Dermatology', 'Shampoo', 27.35, 'Medicated shampoo for fungal and seborrheic skin disease.');
INSERT IGNORE INTO drugs VALUES (24, 'Oclacitinib', 'Dermatology', 'Tablet', 42.70, 'Anti-itch therapy for allergic dermatitis.');
INSERT IGNORE INTO drugs VALUES (25, 'Lime Sulfur Dip', 'Dermatology', 'Topical', 13.20, 'Dip treatment for ringworm and external parasites.');
INSERT IGNORE INTO drugs VALUES (26, 'Cerenia', 'Gastrointestinal', 'Tablet', 36.25, 'Anti-nausea medication for vomiting and motion sickness.');
INSERT IGNORE INTO drugs VALUES (27, 'Omeprazole', 'Gastrointestinal', 'Capsule', 10.80, 'Acid reducer for gastritis and reflux support.');
INSERT IGNORE INTO drugs VALUES (28, 'Metronidazole', 'Gastrointestinal', 'Tablet', 16.95, 'Antimicrobial often used for diarrhea and giardia.');
INSERT IGNORE INTO drugs VALUES (29, 'Sucralfate', 'Gastrointestinal', 'Suspension', 14.60, 'Gastroprotectant for esophageal and stomach irritation.');
INSERT IGNORE INTO drugs VALUES (30, 'Probiotic Paste', 'Gastrointestinal', 'Paste', 12.10, 'Digestive support paste for stress-related diarrhea.');
