INSERT INTO vets (first_name, last_name) SELECT 'James', 'Carter' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=1);
INSERT INTO vets (first_name, last_name) SELECT 'Helen', 'Leary' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=2);
INSERT INTO vets (first_name, last_name) SELECT 'Linda', 'Douglas' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=3);
INSERT INTO vets (first_name, last_name) SELECT 'Rafael', 'Ortega' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=4);
INSERT INTO vets (first_name, last_name) SELECT 'Henry', 'Stevens' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=5);
INSERT INTO vets (first_name, last_name) SELECT 'Sharon', 'Jenkins' WHERE NOT EXISTS (SELECT * FROM vets WHERE id=6);

INSERT INTO specialties (name) SELECT 'radiology' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='radiology');
INSERT INTO specialties (name) SELECT 'surgery' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='surgery'); 
INSERT INTO specialties (name) SELECT 'dentistry' WHERE NOT EXISTS (SELECT * FROM specialties WHERE name='dentistry');

INSERT INTO vet_specialties VALUES (2, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (3, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (3, 3) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (4, 2) ON CONFLICT (vet_id, specialty_id) DO NOTHING;
INSERT INTO vet_specialties VALUES (5, 1) ON CONFLICT (vet_id, specialty_id) DO NOTHING;

INSERT INTO types (name) SELECT 'cat' WHERE NOT EXISTS (SELECT * FROM types WHERE name='cat');
INSERT INTO types (name) SELECT 'dog' WHERE NOT EXISTS (SELECT * FROM types WHERE name='dog');
INSERT INTO types (name) SELECT 'lizard' WHERE NOT EXISTS (SELECT * FROM types WHERE name='lizard');
INSERT INTO types (name) SELECT 'snake' WHERE NOT EXISTS (SELECT * FROM types WHERE name='snake');
INSERT INTO types (name) SELECT 'bird' WHERE NOT EXISTS (SELECT * FROM types WHERE name='bird');
INSERT INTO types (name) SELECT 'hamster' WHERE NOT EXISTS (SELECT * FROM types WHERE name='hamster');

INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=1);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=2);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=3);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=4);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=5);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=6);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=7);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=8);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=9);
INSERT INTO owners (first_name, last_name, address, city, telephone) SELECT 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487' WHERE NOT EXISTS (SELECT * FROM owners WHERE id=10);

INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Leo', '2000-09-07', 1, 1 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=1);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Basil', '2002-08-06', 6, 2 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=2);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Rosy', '2001-04-17', 2, 3 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=3);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Jewel', '2000-03-07', 2, 3 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=4);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Iggy', '2000-11-30', 3, 4 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=5);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'George', '2000-01-20', 4, 5 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=6);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Samantha', '1995-09-04', 1, 6 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=7);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Max', '1995-09-04', 1, 6 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=8);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Lucky', '1999-08-06', 5, 7 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=9);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Mulligan', '1997-02-24', 2, 8 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=10);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Freddy', '2000-03-09', 5, 9 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=11);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Lucky', '2000-06-24', 2, 10 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=12);
INSERT INTO pets (name, birth_date, type_id, owner_id) SELECT 'Sly', '2002-06-08', 1, 10 WHERE NOT EXISTS (SELECT * FROM pets WHERE id=13);

INSERT INTO visits (pet_id, visit_date, description) SELECT 7, '2010-03-04', 'rabies shot' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=1);
INSERT INTO visits (pet_id, visit_date, description) SELECT 8, '2011-03-04', 'rabies shot' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=2);
INSERT INTO visits (pet_id, visit_date, description) SELECT 8, '2009-06-04', 'neutered' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=3);
INSERT INTO visits (pet_id, visit_date, description) SELECT 7, '2008-09-04', 'spayed' WHERE NOT EXISTS (SELECT * FROM visits WHERE id=4);

INSERT INTO drugs (name, category, form, price, description) SELECT 'Amoxicillin', 'Antibiotic', 'Tablet', 18.50, 'Broad-spectrum antibiotic for common bacterial infections.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Amoxicillin');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Clavamox', 'Antibiotic', 'Tablet', 24.99, 'Combination antibiotic for skin and dental infections.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Clavamox');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Cefpodoxime', 'Antibiotic', 'Tablet', 31.75, 'Once-daily cephalosporin for canine skin infections.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Cefpodoxime');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Doxycycline', 'Antibiotic', 'Capsule', 19.90, 'Tetracycline antibiotic often used for tick-borne diseases.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Doxycycline');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Cefovecin', 'Antibiotic', 'Injectable', 57.25, 'Long-acting injectable antibiotic for cats and dogs.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Cefovecin');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Milbemycin', 'Antiparasitic', 'Tablet', 14.25, 'Monthly heartworm prevention with intestinal parasite coverage.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Milbemycin');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Fenbendazole', 'Antiparasitic', 'Suspension', 12.80, 'Dewormer for roundworms, hookworms, and giardia.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Fenbendazole');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Selamectin', 'Antiparasitic', 'Topical', 22.40, 'Topical treatment for fleas, ear mites, and heartworm prevention.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Selamectin');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Pyrantel Pamoate', 'Antiparasitic', 'Suspension', 9.60, 'Oral dewormer commonly used in puppies and kittens.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Pyrantel Pamoate');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Ivermectin', 'Antiparasitic', 'Injectable', 16.30, 'Antiparasitic used for mange and parasite control.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Ivermectin');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Carprofen', 'Pain Management', 'Chewable', 28.45, 'NSAID chewable for canine postoperative pain.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Carprofen');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Gabapentin', 'Pain Management', 'Capsule', 17.20, 'Neuropathic pain support and mild anxiolytic.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Gabapentin');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Tramadol', 'Pain Management', 'Tablet', 21.15, 'Oral analgesic for short-term pain relief.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Tramadol');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Buprenorphine', 'Pain Management', 'Injectable', 34.80, 'Opioid analgesic for moderate pain control.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Buprenorphine');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Amantadine', 'Pain Management', 'Capsule', 13.95, 'Adjunct pain medication for chronic discomfort.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Amantadine');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Meloxicam', 'Anti-inflammatory', 'Suspension', 23.50, 'Oral NSAID for inflammation and osteoarthritis pain.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Meloxicam');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Deracoxib', 'Anti-inflammatory', 'Chewable', 29.10, 'COX-2 selective NSAID for canine inflammation.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Deracoxib');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Firocoxib', 'Anti-inflammatory', 'Tablet', 33.60, 'Once-daily anti-inflammatory for osteoarthritis.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Firocoxib');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Prednisolone', 'Anti-inflammatory', 'Tablet', 11.75, 'Corticosteroid for inflammatory and immune-mediated conditions.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Prednisolone');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Triamcinolone', 'Anti-inflammatory', 'Injectable', 26.55, 'Injectable corticosteroid for acute inflammatory flare-ups.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Triamcinolone');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Chlorhexidine Spray', 'Dermatology', 'Topical', 15.40, 'Antiseptic spray for superficial skin infections.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Chlorhexidine Spray');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Mupirocin', 'Dermatology', 'Ointment', 18.90, 'Topical antibiotic ointment for localized lesions.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Mupirocin');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Ketoconazole Shampoo', 'Dermatology', 'Shampoo', 27.35, 'Medicated shampoo for fungal and seborrheic skin disease.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Ketoconazole Shampoo');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Oclacitinib', 'Dermatology', 'Tablet', 42.70, 'Anti-itch therapy for allergic dermatitis.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Oclacitinib');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Lime Sulfur Dip', 'Dermatology', 'Topical', 13.20, 'Dip treatment for ringworm and external parasites.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Lime Sulfur Dip');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Cerenia', 'Gastrointestinal', 'Tablet', 36.25, 'Anti-nausea medication for vomiting and motion sickness.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Cerenia');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Omeprazole', 'Gastrointestinal', 'Capsule', 10.80, 'Acid reducer for gastritis and reflux support.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Omeprazole');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Metronidazole', 'Gastrointestinal', 'Tablet', 16.95, 'Antimicrobial often used for diarrhea and giardia.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Metronidazole');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Sucralfate', 'Gastrointestinal', 'Suspension', 14.60, 'Gastroprotectant for esophageal and stomach irritation.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Sucralfate');
INSERT INTO drugs (name, category, form, price, description) SELECT 'Probiotic Paste', 'Gastrointestinal', 'Paste', 12.10, 'Digestive support paste for stress-related diarrhea.' WHERE NOT EXISTS (SELECT * FROM drugs WHERE name='Probiotic Paste');
